package com.mtjanney.killeffects.effects.utilities;

public enum Effects {
    NULL,
    BUBBLE_POP,
    CAMPFIRE,
    CLOUD,
    CRIT,
    CRIT_MAGIC,
    DRAGON_BREATH,
    DRIP_LAVA,
    DRIP_WATER,
    ELECTRIC_SPARK,
    ENCHANTMENT_TABLE,
    END_ROD,
    EXPLOSION_LARGE,
    FALLING_HONEY,
    FALLING_OBSIDIAN_TEAR,
    FIREWORKS_SPARK,
    FLAME,
    GLOW_SQUID_INK,
    HEART,
    NOTE,
    PORTAL,
    SNOWFLAKE,
    SOUL_FIRE_FLAME,
    TOTEM,
    VILLAGER_ANGRY,
    VILLAGER_HAPPY
}
